INFERENCE:
  checkpoint_type: epoch_idx
  dictionary_path: ../../../dataset/representations/uncond/remi/ailab17k_from-scratch_remi/dictionary.pkl
  experiment_dir: /import/c4dm-05/pps30/exp_architecture/exp_2/5_lat102420211006-162944
  generated_dir: ./gen_midis
  gpuID: '0'
  model_epoch: 100
  no_cuda: false
  num_sample: 150
MODEL:
  clamp_len: -1
  d_embed: 512
  d_inner: 4096
  d_model: 1024
  div_val: 1
  dropatt: 0.0
  dropout: 0.1
  emb_init: normal
  emb_init_range: 0.01
  eval_tgt_len: 50
  ext_len: 0
  init: normal
  init_range: 0.1
  init_std: 0.02
  mem_len: 512
  n_head: 8
  n_layer: 10
  n_token: 3020
  position_concat: false
  pre_lnorm: true
  proj_init_std: 0.01
  query_dim: 16
  same_length: true
  seq_len: 512
  tgt_len: 70
TRAIN:
  ROOT: ../../../dataset/representations/uncond/remi/ailab17k_from-scratch_remi
  batch_size: 8
  experiment_Dir: /import/c4dm-05/pps30/exp_architecture/exp_2/5_lat102420220411-164534
  gpuID: '0'
  lr: 0.0001
  no_cuda: false
  num_epochs: 200
  optim: adam
  output_dir: /import/c4dm-05/pps30/exp_architecture/exp_2
  resume_training_model: ./model-weights/ep_200.pth.tar
  save_freq: 10
  seed: 2222
